require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClientListsController do

  # This should return the minimal set of attributes required to create a valid
  # ClientList. As you add validations to ClientList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "client" => "MyString", "description" => "My Description" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClientListsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all client_lists as @client_lists" do
      client_list = ClientList.create! valid_attributes
      get :index, {}, valid_session
      assigns(:client_lists).should eq([client_list])
    end
  end

  describe "GET show" do
    it "assigns the requested client_list as @client_list" do
      client_list = ClientList.create! valid_attributes
      get :show, {:id => client_list.to_param}, valid_session
      assigns(:client_list).should eq(client_list)
    end
  end

  describe "GET new" do
    it "assigns a new client_list as @client_list" do
      get :new, {}, valid_session
      assigns(:client_list).should be_a_new(ClientList)
    end
  end

  describe "GET edit" do
    it "assigns the requested client_list as @client_list" do
      client_list = ClientList.create! valid_attributes
      get :edit, {:id => client_list.to_param}, valid_session
      assigns(:client_list).should eq(client_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ClientList" do
        expect {
          post :create, {:client_list => valid_attributes}, valid_session
        }.to change(ClientList, :count).by(1)
      end

      it "assigns a newly created client_list as @client_list" do
        post :create, {:client_list => valid_attributes}, valid_session
        assigns(:client_list).should be_a(ClientList)
        assigns(:client_list).should be_persisted
      end

      it "redirects to the created client_list" do
        post :create, {:client_list => valid_attributes}, valid_session
        response.should redirect_to(ClientList.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved client_list as @client_list" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClientList.any_instance.stub(:save).and_return(false)
        post :create, {:client_list => { "client" => "invalid value" }}, valid_session
        assigns(:client_list).should be_a_new(ClientList)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClientList.any_instance.stub(:save).and_return(false)
        post :create, {:client_list => { "client" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested client_list" do
        client_list = ClientList.create! valid_attributes
        # Assuming there are no other client_lists in the database, this
        # specifies that the ClientList created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ClientList.any_instance.should_receive(:update).with({ "client" => "MyString" })
        put :update, {:id => client_list.to_param, :client_list => { "client" => "MyString" }}, valid_session
      end

      it "assigns the requested client_list as @client_list" do
        client_list = ClientList.create! valid_attributes
        put :update, {:id => client_list.to_param, :client_list => valid_attributes}, valid_session
        assigns(:client_list).should eq(client_list)
      end

      it "redirects to the client_list" do
        client_list = ClientList.create! valid_attributes
        put :update, {:id => client_list.to_param, :client_list => valid_attributes}, valid_session
        response.should redirect_to(client_list)
      end
    end

    describe "with invalid params" do
      it "assigns the client_list as @client_list" do
        client_list = ClientList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClientList.any_instance.stub(:save).and_return(false)
        put :update, {:id => client_list.to_param, :client_list => { "client" => "invalid value" }}, valid_session
        assigns(:client_list).should eq(client_list)
      end

      it "re-renders the 'edit' template" do
        client_list = ClientList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClientList.any_instance.stub(:save).and_return(false)
        put :update, {:id => client_list.to_param, :client_list => { "client" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested client_list" do
      client_list = ClientList.create! valid_attributes
      expect {
        delete :destroy, {:id => client_list.to_param}, valid_session
      }.to change(ClientList, :count).by(-1)
    end

    it "redirects to the client_lists list" do
      client_list = ClientList.create! valid_attributes
      delete :destroy, {:id => client_list.to_param}, valid_session
      response.should redirect_to(client_lists_url)
    end
  end

end
